#!/usr/bin/env python

from __future__ import print_function

import os
import sys
from leylab_pipelines import Leylab_pipelines


# main
if __name__ == '__main__':
    Leylab_pipelines.LLP_DB_arg_parse()
